ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/LIFT2DICT.java"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/LIFT2DICT.java~"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/LIFT2DICTServlet.java"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/LIFT2DICTServlet.java~"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2Dict.java"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2Dict.java~"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2Html.java"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2MxDict.java~"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Dict.java"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Dict.java~"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Html.java"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2MxDict.java~"
ls -l "/home/tjm/Documents/tomcat6webapps/webapps/flexelan/WEB-INF/classes/com/ntopus/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenSA/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenSA (1)/Lift2Html2013/Lift2Html20130417/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenSA (1)/Lift2Html2013/Lift2Html20130418/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenSA (1)/Lift2Html2013/Lift2Html20130419/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenSA (1)/Lift2Html2013/miscPreIdesOfApril/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenTech/ItelmenSA/Lift2Html2013/Lift2Html20130417/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenTech/ItelmenSA/Lift2Html2013/Lift2Html20130418/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenTech/ItelmenSA/Lift2Html2013/Lift2Html20130419/Lift2Html.java"
ls -l "/home/tjm/Dropbox/ItelmenTech/ItelmenSA/Lift2Html2013/miscPreIdesOfApril/Lift2Html.java"
ls -l "/home/tjm/Dropbox/Proj2013/mannx/MXH5/WEB-INF/classes/com/ntopus/Lift2Dict.java"
ls -l "/home/tjm/Dropbox/Proj2013/mannx/MXH5/WEB-INF/classes/com/ntopus/Lift2ErrList.java"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2DictOld.java"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2ErrList.java"
ls -l "/var/lib/tomcat7/webapps/MXH5/WEB-INF/classes/com/ntopus/Lift2Html.java"
ls -l "/var/lib/tomcat7/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Dict.java"
ls -l "/var/lib/tomcat7/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Dict.java~"
ls -l "/var/lib/tomcat7/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2Html.java"
ls -l "/var/lib/tomcat7/webapps/flexelan/Lift2Html/dict/classes/com/ntopus/Lift2MxDict.java~"
ls -l "/var/lib/tomcat7/webapps/flexelan/WEB-INF/classes/com/ntopus/Lift2Html.java"
